"""new user data db

Revision ID: 24e80ad94507
Revises: 5785e6ef2543
Create Date: 2016-02-19 13:02:02.895744

"""

# revision identifiers, used by Alembic.
revision = '24e80ad94507'
down_revision = '5785e6ef2543'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('realname', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'realname')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'create_date')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
