"""new poat.body_html2

Revision ID: 432ffc280c2b
Revises: 39ba9b7bef7c
Create Date: 2016-03-04 21:34:44.919470

"""

# revision identifiers, used by Alembic.
revision = '432ffc280c2b'
down_revision = '39ba9b7bef7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
