"""new comment

Revision ID: 551186510b2
Revises: 453042c29a59
Create Date: 2016-03-07 16:40:22.486212

"""

# revision identifiers, used by Alembic.
revision = '551186510b2'
down_revision = '453042c29a59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_timestamp'), 'commit', ['timestamp'], unique=False)
    op.add_column(u'posts', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['post_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column(u'posts', 'post_id')
    op.drop_index(op.f('ix_commit_timestamp'), table_name='commit')
    op.drop_table('commit')
    ### end Alembic commands ###
