"""new add disabled in comment

Revision ID: 882fb6d3bbf
Revises: 551186510b2
Create Date: 2016-03-07 22:40:16.840444

"""

# revision identifiers, used by Alembic.
revision = '882fb6d3bbf'
down_revision = '551186510b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'disabled')
    ### end Alembic commands ###
