#-*- encoding=utf-8 -*-
"""更正realname为real_name

Revision ID: dd2d6effc10
Revises: 24e80ad94507
Create Date: 2016-02-19 17:55:47.690321

"""

# revision identifiers, used by Alembic.
revision = 'dd2d6effc10'
down_revision = '24e80ad94507'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=64), nullable=True))
    op.drop_column('users', 'realname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('realname', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'real_name')
    ### end Alembic commands ###
